## Practicum Assesment

### Question 1.1: Download the Dataset  - 30mins for Question1

In [1]:
## Lets go ahead and import the necessary libaries we may need for this task

import numpy as np     ##numpy lib
import pandas as pd    ##pandas lib
from matplotlib import pyplot as plt   ##matplotlib lib
import plotly.express as px   ##plotly lib

In [2]:
## Lets read our dataframe and store it in a variable name: 'df'
df =pd.read_csv(r'C:\Users\IamFavoured\Desktop\IKEBUKWU\Python_pro\Practicum_Dataset\movie_metadata.csv')  ## reading our file from a folder explicitly
df.head()    ## The first 5 records in our dataset

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  ...  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  ...   
1                 40000.0  309404152.0         Action|Adventure|Fantasy  ...   
2                 11000.0  200074175.0        Action|Adventure|Thriller  ...   
3                 27000.0  448130642.0                  Action|Thriller  ...   
4                   131.0          NaN                      Documentary  ...   

  num_user_for_reviews language  country  content_rating        budget  \
0               3054.0  English      USA           PG-13  237000000.0$   
1               1238.0  English      USA           PG-13  300000000.0$   
2                994.0  English       UK           PG-13  245000000.0$   
3               2701.0  English      USA           PG-13  250000000.0$   
4                  NaN      NaN      NaN             NaN          0.0$   

   title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0      2009.0                  936.0        7.9          1.78   
1      2007.0                 5000.0        7.1          2.35   
2      2015.0                  393.0        6.8          2.35   
3      2012.0                23000.0        8.5          2.35   
4         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

### Question1.2: The number of null values in 'duration' column?

In [3]:
### Lets get all the columns in our dataset

df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [4]:
### There are quite alot of columns in our dataframe:
### Lets use another method to check if the desired column is in our dataframe

if 'duration' in df.columns:
    print('True')
else :
    print('False')

True


In [5]:
## To check the number of null values in our column
## We got 15...Yipee!!

df['duration'].isnull().sum()

15

### Question1.3: Replace the missing values in the duration column with the median value for this column

In [6]:
## There are several ways to do this: we could use imputer lib in sklearn, fillna, replace fn etc
## Lets find out what the median value for the column is

df['duration'].median()

103.0

In [7]:
## Lets fill it with the median

df['duration'].fillna(value=df['duration'].median(), inplace=True)

In [8]:
## Lets check how many null values we have after the above operation

df['duration'].isnull().sum()

0

### Question 1.4. What is the average film length? Give the answer as a floating-point figure rounded to two decimal place

In [9]:
## We can easily do this with a round fn

round(df['duration'].mean(),2)

107.19

### Question 1.5. How many films between 90 minutes and two hours long were released in 2008?

In [12]:
### There are severral ways to query our df
### Lets use the below
### There are 160 films within this constraints

df[(df.title_year == 2008.) & (df.duration >=90) & (df.duration <=120)].shape[0]

160

### Question 1.6. The budget column contains the film's budget. What is the median budget for all the films listed? Give the answer as an integer.

In [ ]:
## We can do this with the function below

df['budget'].median()  ## Encountered an error while performing this; the budget column is an object data type

In [14]:
## Lets view the column
df.budget.head()

0    237000000.0$
1    300000000.0$
2    245000000.0$
3    250000000.0$
4            0.0$
Name: budget, dtype: object

In [15]:
## Lets remove the $ character then
## convert the budget column to an integer

df.budget= df.budget.str.replace('$','',regex=True)
df.budget=pd.to_numeric(df.budget).astype(int)

In [18]:
int(df['budget'].median())

## Median for all the movie is 15,000,000 USD

15000000

## Question 2: What is the difference between DataFrame and Series? -- 10mins for Question 2

In [19]:
## First we need to understand what data is?
## Data is the collection of facts, concepts, information for reference or analysis purposes
## Data is further classified into 2 : textual and non-textual data
## Textual data : numbers, alphabets
## Non-textual data : pictures, audiotapes, videos, finger print etc
## Most textual data are stored in a table formats for easy interpretation and understanding
## Table formats are combination of rows and columns
## Rows are arranged from left to right
## Columns move from top to bottom
## see below for example

#### Rows

In [20]:
np.arange(10)  ## Moves from left to right

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Columns

In [21]:
np.arange(10).reshape(-1,1)  ## Moves from top to bottom

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [22]:
## The above illustration makes it easier to understand the below explanation
## Series are a single row or Column
## Dataframe are combination of Series
## The above are series
## See below dataframe

#### Dataframe

In [23]:
np.eye(3)  ## Contains multiple rows and columns
## Hope this helps
## Any questions?

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Question 3   --15mins for Question 3

#### $$ E(X) = 0.5, Var(X) = 2 $$
#### $$ E(Y) = 7, Var(Y) = 3.5 $$
#### $$ cov (X, Y) = -0.8 $$
#### Find the variance of the random variable Z = 2X - 3Y

### $$ Var(z)=Var(2X-3Y)  $$
### $$ Var(2X-3Y)= 2^2Var(X)+ (-3)^2Var(Y) + 2(2)(-3)Cov(X,Y)  $$
### $$ Var(2X-3Y)= 4*2+ 9*3.5 + 2(2)(-3)(-0.8)  $$
### $$ Var(2X-3Y)= 8+ 31.5 + 9.6  $$
### $$ VarZ=Var(2X-3Y)= 49.1  $$
### $$ VarZ=49.1  $$

## Question 4. Task for Data Science course -- 10mins for Question 4

## $$ MSE= \frac{1}{n}\sum_{i=1}^n (Y_i - \bar{Y_i})^2  $$

#### OMER MSE

#### $$ MSE= \frac{((-0.5^2)*400)+((0.7^2)*100)}{500} $$
#### $$ MSE= \frac{100+49}{500} $$
#### $$ MSE= 0.298 $$

#### LIMOR MSE

In [172]:
### Assuming limor found the smallest error
### Lets Assume the error(difference) between the observed and predicted value is 0.3

#### $$ MSE= \frac{(0.3^2)*500}{500} $$
#### $$ MSE= \frac{45}{500} $$
#### $$ MSE= 0.09 $$